Namespace Beacon
    Public NotInheritable Class HelpTopic
        Public ReadOnly Property Title As String
        Public ReadOnly Property Body As String
        Public Property DocumentationUrl As String
        Public Sub New(title As String, ParamArray paragraphs As String())
            Me.Title = title
            Body = String.Join(vbCrLf & vbCrLf, paragraphs)
        End Sub
    End Class

    Public NotInheritable Class HelpContent
        Private Sub New()
        End Sub
        Public Shared Function Topics() As List(Of HelpTopic)
            Dim catalog As New List(Of HelpTopic) From {
                New HelpTopic("Start here — your first search",
                    "WHAT BEACON DOES" & vbCrLf & "Beacon helps you find information without opening every file yourself. Choose a folder or archive, enter the words you want, and Beacon lists the files where it finds them. You can then read the matching lines, Windows events, or saved web requests.",
                    "1. Click Folder to choose a folder, or Archive to choose an archive. Path shows your selection; it cannot be edited directly.",
                    "2. In Search mode, choose Literal text. In Search for, enter ""error"". Leave Case sensitive unchecked to find both ""error"" and ""ERROR"".",
                    "3. Click Scan. Wait while Beacon counts files and then searches them. Counting large archives can take time.",
                    "4. Select a file in Matched Files on the left. Read its preview on the right. Expand Match details below the file list and select a location to jump to it.",
                    "WHAT YOU SHOULD SEE" & vbCrLf & "If the chosen files contain ""error"", matching files appear in the list and available matches are highlighted in the preview. An empty list means no matches were collected; see Troubleshooting if you expected some.",
                    "HOW TO READ EXAMPLES" & vbCrLf & "This guide puts example inputs inside double quotes for readability. Do not type those surrounding quotes unless an instruction explicitly says to keep them. For the example ""error"", type only the five letters. Phrase searches in Any term and All terms are the exception, explained in Search modes."),
                New HelpTopic("Search modes",
                    "CHOOSE HOW TO MATCH" & vbCrLf & "Use the Search mode dropdown beside Search for, enter your text, then click Scan. Start with Literal text; you do not need regex for a normal word or phrase. Example-label quotes are not part of the input unless stated otherwise.",
                    "Literal text — use this for a word, phrase or exact punctuation. Input: ""connection failed"". Finds: ""The connection failed yesterday"". Does not find: ""connection was interrupted"". Spaces belong to the phrase.",
                    "Whole word: finds a word on its own. For example, ""cat"" matches ""a cat"" but not ""catalog"".",
                    "Regular expression — use a pattern when the value changes, for example ""code=\d+"" to find ""code=123"" or ""code=7"". See Regex 1 — your first pattern for a guided lesson and Regex 4 — common recipes for ready-to-use examples.",
                    "Any term: finds a record containing at least one term. For example, ""error timeout"" finds records containing either word.",
                    "All terms — input ""error timeout"" to require both words in the same text line, event or saved web request, in either order. Finds: ""timeout caused an error"". Does not find: ""error only"".",
                    "KEEPING A PHRASE TOGETHER" & vbCrLf & "In Any term or All terms, keep the double quotes around ""connection failed"" if you want those words together. To require that phrase plus another word: type the quoted phrase, a space, then ""timeout"" without quotes. The actual field should contain:" & vbCrLf & "  ""connection failed"" timeout" & vbCrLf & "This line includes the quotes you must type. In Literal text mode, leave phrase quotes out.",
                    "Case sensitive controls capitalization in each mode. A search with it unchecked can match uppercase and lowercase text. Any term and All terms accept up to 32 words/phrases; the whole search is limited to 4,096 characters."),
                New HelpTopic("Changing a search, cancelling and Reset",
                    "RUN A DIFFERENT SEARCH" & vbCrLf & "1. Change Search for or choose a different source with Folder or Archive." & vbCrLf & "2. Click Scan." & vbCrLf & "Expected result: Beacon replaces the previous result list with the new search. Until you scan again, the old results and highlights remain unchanged.",
                    "While a scan is running, click Cancel or press Esc to stop it. Results collected so far remain available, but they may not include every matching file or record.",
                    "Reset clears the current search and results so you can start again. Export any results you want to keep before resetting. Reset is different from Restore defaults in Settings, which resets configuration values."),
                New HelpTopic("Counts, multiple matches and partial results",
                    "UNDERSTAND THE NUMBERS" & vbCrLf & "A matching file contains something you searched for. Inside it, Beacon collects matching records: a line in a text file, an event in an EVTX file, or a request in a HAR file. Several highlighted words can belong to a single record.",
                    "If you see only one event or request, open Settings → Search and uncheck 'Stop after the first matching line, event, or request per file'. Save and rerun the scan. Older saved preferences are preserved, so an existing installation may still have this checked. Existing results cannot grow when you change Settings.",
                    "COLLECT MORE MATCHES" & vbCrLf & "1. Open Settings → Search and check Maximum detailed records per file." & vbCrLf & "2. For events or requests, also check their matching-record limit under EVTX and HAR." & vbCrLf & "3. Save and scan again. The smaller applicable limit wins. Example: a general limit of ""100"" and an event limit of ""300"" allow at most 100 matching events per file. Larger limits use more memory and time.",
                    "A + after a result count means the captured results are partial; hover over it for the reason. The counted/scanned file total is not the number of matching files. It counts eligible sources, including files with no match. Archive containers are not added again on top of their contents.",
                    "Cancelled scans, read failures, changing source files and safety limits can leave the scanned count below the pre-counted total. Visible events/requests may also be fewer than captured records because of preview filters. Clear those filters to see all captured records."),
                New HelpTopic("Reading previews and navigating results",
                    "Select a matching file on the left to open its preview. Drag the divider to change the space available to the file list and preview. Expand or collapse Match details at the bottom of the left pane when you need individual locations.",
                    "Text files use a selectable text preview. HTML, XML and JSON previews may use the installed WebView2 runtime. If browser preview is unavailable, Beacon can fall back to text. Preview limits can shorten content; do not mistake a bounded preview for the entire source.",
                    "Find Next moves through highlighted matches. In event previews, it searches within the current event before advancing to another visible event. Request navigation moves between visible captured requests. Next File selects another matching file.",
                    "WHY A MATCH MAY NOT BE HIGHLIGHTED" & vbCrLf & "The match may be in the file name or path rather than the displayed content. HAR privacy settings can hide matching values. Document previews can format text differently from the searched text. Regex lookarounds can also match a position without selecting letters; see Regex 5 — troubleshooting. Changing Search for does not update an existing preview until you rescan."),
                New HelpTopic("EVTX — Windows event logs",
                    "WHEN TO USE THIS" & vbCrLf & "Windows records activity and problems as events. An EVTX file is a saved collection of those events. Search it when investigating a crash, failed sign-in, service error or another Windows problem. The provider is the component that wrote the event; the event ID identifies a kind of event, not how many matches were found.",
                    "SEARCH EVENTS" & vbCrLf & "1. Choose the folder or archive containing your EVTX files." & vbCrLf & "2. Enter a search such as ""error"" in Literal text mode and click Scan." & vbCrLf & "3. Select an EVTX result. Read its ID, provider, time and message. Expand Match details to select a particular matching event.",
                    "NARROW WHAT YOU SEE" & vbCrLf & "1. Open Event tools at the right edge of the preview." & vbCrLf & "2. Choose Error in Severity levels and click Apply filters." & vbCrLf & "Expected result: only captured matching error events are shown. Click Clear filters to show the other captured events again. Collapsing Event tools does not clear its filters.",
                    "FILTER BEFORE SEARCHING" & vbCrLf & "Use Settings → EVTX and HAR to restrict the next scan by event ID, provider, severity or time. Example: enter ""1000,1001"" for either event ID. Blank fields leave that choice unrestricted; different filters must all match. Save and rescan. Unlike these Settings filters, Event tools only changes what you see: exports still include all results from the scan. Selecting an explicit Match details entry clears preview filters to make the jump possible.",
                    "Raw event XML stays below the message. Expand it to inspect the structured data or use Copy XML. XML may contain sensitive information. Captures are bounded; copying is disabled for shortened XML so an incomplete document is not presented as complete.",
                    "IF THE MESSAGE IS MISSING" & vbCrLf & "The event can still exist even when this computer cannot explain its message. Read Raw event XML and the missing-message guidance in Event tools. For the advanced source-machine export steps, see Missing event messages — advanced help."),
                New HelpTopic("Missing event messages — advanced help",
                    "WHY THIS HAPPENS" & vbCrLf & "Windows sometimes needs files from the event's provider to turn event data into a readable sentence. Those files may be missing on a different computer. Beacon can still search the raw XML; it does not download or register provider DLLs.",
                    "WHAT TO ASK THE SOURCE COMPUTER'S OWNER" & vbCrLf & "Export the log with display information where offered. A Windows administrator can also use ""wevtutil al"" to archive a COPY in a trusted working folder. This is a Windows command, not text to enter in Beacon. Keep the exported EVTX and its LocaleMetaData folder together and open from disk. Beacon's individual archive-entry extraction does not automatically bring sibling locale metadata.",
                    "SAFETY NOTE" & vbCrLf & "Do not alter original evidence or use untrusted symbolic-link/junction destinations. If you are unfamiliar with log export, ask the source system administrator for a portable copy rather than downloading DLLs from a website."),
                New HelpTopic("Dates, providers and severity selectors",
                    "CHOOSE A TIME RANGE" & vbCrLf & "Use From and To to narrow a search to a period. Both boundary times are included. UTC is a shared world time, which may differ from your local clock: convert local incident times to UTC before entering them.",
                    "Type a date/time directly as ""yyyy-MM-dd HH:mm:ss"" or ""yyyy-MM-ddTHH:mm:ssZ"". Example: ""2026-01-02 09:30:00"". Or open the date picker, type individual year/month/day/hour/minute/second values, and use arrows or Up/Down keys to adjust them.",
                    "1. Open the arrow button beside From or To." & vbCrLf & "2. Type the year, month, day, hour, minute and second, or adjust them with the arrows." & vbCrLf & "3. Click Apply (or Enter). Expected result: that field shows your chosen UTC time. Cancel/Escape keeps the old value; Any time removes the bound. A missing event/request timestamp cannot pass a time filter. From must not be later than To.",
                    "Provider dropdowns suggest names from captured events where available. You can also type a provider before scanning. Blank means any provider. Severity lets you check multiple named levels: Always, Critical, Error, Warning, Information or Verbose. All levels removes the restriction."),
                New HelpTopic("HAR — web requests and responses",
                    "WHEN TO USE THIS" & vbCrLf & "A HAR file is a saved record of a browser's web requests and the server's replies. It helps investigate a website that fails or responds slowly. Beacon reads the saved file; it does not visit the website or repeat requests.",
                    "READ A REQUEST" & vbCrLf & "1. Scan a folder/archive containing the HAR for a word you expect in it." & vbCrLf & "2. Select a HAR result, then a request in Match details." & vbCrLf & "3. Read the method (action, such as ""GET""), URL (address), status (server outcome), duration, headers (extra information), and body (sent/received content). Some content may be hidden by privacy settings.",
                    "FIND FAILED OR SLOW REQUESTS" & vbCrLf & "Open HAR tools, enter ""500,503"" in Status codes, and click Apply filters. Expected result: only captured requests with either status are shown. Add a minimum duration of ""1000"" to also require at least one second. Host accepts an exact name such as ""example.com""; response MIME accepts text such as ""json"" to narrow the content type. All filled-in filters must match.",
                    "SEARCH SCOPE VERSUS VIEW" & vbCrLf & "Settings → EVTX and HAR applies these filters to the next scan: save and rescan. HAR tools narrows only the results you already collected; Clear filters restores those results, not requests missed by earlier limits. Exports retain every captured request regardless of the HAR tools view.",
                    "Maximum request/response body size limits body inspection separately from file/archive size. Base64 decoding can reveal encoded UTF-8 text when enabled. Invalid, binary, unknown-encoding or oversized bodies are omitted with a notice. The file is still parsed within the overall input limits; large HAR files can require significant memory."),
                New HelpTopic("HAR privacy and redaction",
                    "WHY VALUES ARE HIDDEN" & vbCrLf & "HAR files can contain passwords, cookies and access tokens. The redaction option hides some of these values in previews and reports. Beacon searches the original data it is allowed to read, so a result can say the match is hidden rather than display the secret you searched for.",
                    "Redaction hides header values, URL query values/user information/fragments and recognized secret fields in JSON/form data. Unstructured or unsupported bodies are withheld. This can explain why a matching request has no visible highlight or why a response body is not shown.",
                    "This is NOT full anonymization. Search terms, file paths, URL paths, server addresses, field names, unrecognized JSON values and non-HAR results may still be sensitive. Always review reports and copied content before sharing.",
                    "IF YOU NEED ORIGINAL VALUES" & vbCrLf & "Only if authorized: open Settings → EVTX and HAR, uncheck Redact captured HAR preview and export data, save, and scan again. The new results can expose secrets; do not share them casually. Existing hidden results cannot reveal removed values without a new scan. Beacon does not rewrite the original HAR file."),
                New HelpTopic("Archives, file access and safeguards",
                    "SEARCH A COMPRESSED FILE" & vbCrLf & "1. Click Archive and select a supported archive, such as a ZIP or CAB." & vbCrLf & "2. Enter your search and click Scan." & vbCrLf & "Expected result: matching files inside it appear in Matched Files. You can also choose a folder that contains archives. Beacon can read ZIP, 7z, RAR, TAR, supported compressed TARs and CAB without you manually extracting them first.",
                    "Settings → Archives controls nesting depth, entry count, entry size, expanded size, compression ratio and external-process timeout. Depth 0 means do not enter an archive inside another archive. Safety limits can stop an archive early; inspect Diagnostics rather than assuming no matches exist.",
                    "Encrypted entries, unsafe paths and archive links are rejected. Integrity failures are reported rather than ignored. First-match/cancelled reads do not certify the integrity of unread content. Use trusted sources and keep the app updated.",
                    "Settings → Files and access controls included text extensions, excluded directory names, maximum file size, hidden/system files and following symbolic links or junctions. Specialized EVTX/HAR/archive handling is separate from the text-extension list.",
                    "For access denied, Beacon can skip/report or ask about ownership recovery. Ownership changes require your confirmation and possibly Windows administrator approval, affect the indicated path, and may still not grant read access. Never change ownership of system or evidence files casually."),
                New HelpTopic("Exporting, copying and Diagnostics",
                    "SAVE RESULTS TO READ OR SHARE" & vbCrLf & "1. Run a search." & vbCrLf & "2. Click Export… below the preview." & vbCrLf & "3. Choose a file name and location, then save." & vbCrLf & "Expected result: an HTML file you can open in a browser, with results grouped by file and up to five nearby lines per match. It includes its own logo and styling; you do not need to send companion image files.",
                    "Reports describe the query and settings captured for that scan, including EVTX/HAR pre-scan filters and partial coverage. Preview-only filters do not remove results from an export. Export uses captured snippets instead of rereading source files. Cancel export stops a write without replacing an existing report with a partial file.",
                    "COPY LOCATIONS OR XML" & vbCrLf & "Click Copy paths to copy the matching files' locations, including where they sit inside archives. For an event's data, expand Raw event XML and click Copy XML. Review copied data before sharing it.",
                    "FIND OUT WHY FILES WERE SKIPPED" & vbCrLf & "Click Diagnostics. Read the source and explanation for each problem. Filter by text or severity to find a particular issue; Refresh shows the latest snapshot and Copy all diagnostics copies the list. Diagnostics explains problems—it is not the report of successful matches. Technical details may contain private information.",
                    "No diagnostics does not mean an unlimited search: the results still reflect your targets, filters and configured limits. Review coverage and + indicators."),
                New HelpTopic("Settings, themes and application behavior",
                    "CHANGE A SETTING" & vbCrLf & "Finish or cancel the current scan, then open Settings beside Help. Choose the relevant tab, change the option and click Save. Cancel discards unsaved edits. Restore defaults changes the dialog values; click Save if you want to keep that reset. Changes to searching require a new scan.",
                    "CHOOSE WHERE TO LOOK" & vbCrLf & "Under Search, select file contents to find words inside a file, file names to find a name such as ""server.log"", or full paths to find text in a location such as ""Logs"". If you select several options, any one can make a file appear in the results. This is separate from the Search mode that controls how your words match.",
                    "MAKE READING COMFORTABLE" & vbCrLf & "Open Preview and diagnostics to choose an installed font and size, wrap long text lines, limit preview size, format JSON/XML, select the first result automatically or display full result paths. Choose Light, Dark or System theme under Appearance and save; System follows Windows app colors. Diagnostic detail controls how much technical information appears for problems.",
                    "Some advanced controls are reserved for later work: the scan worker count is not currently a parallelism guarantee. Do not assume increasing it makes scanning faster. Missing-provider downloads are not implemented; only the offline workflow is supported.",
                    "Beacon is single-instance per Windows user/session. Launching it again requests activation of the existing window or dialog. Windows foreground-focus rules still apply. Temporary archive data is cleaned up during reset/shutdown; do not remove it while a scan or preview uses it."),
                New HelpTopic("Updates, help and feedback",
                    "At startup Beacon checks for a newer stable GitHub release without blocking the app. A brief notification above the main desktop taskbar counts down from five seconds. View release opens the release page; the close button dismisses it. There are no automatic downloads or installations.",
                    "For a result you can read at your own pace, use Settings → Preview and diagnostics → Updates → Check for updates. The message stays inside Settings and distinguishes a newer version, no updates pending and an unsuccessful check. Offline startup checks fail silently.",
                    "FIND AN ANSWER" & vbCrLf & "Help works offline. Type a few words such as ""only one event"" or ""regex digits"" in Search help, then choose a topic. Clear restores the full list. Regex topics include an optional Microsoft documentation link; opening that link needs internet access. Feedback in Beacon's status bar opens the project's GitHub discussions. Remove private data before posting."),
                New HelpTopic("Keyboard shortcuts",
                    "Enter: start a scan when the Scan button is available. Esc: cancel an active scan. Avoid pressing Enter in the main window while composing a filter if you do not intend to scan.",
                    "F3: next match in the text preview, next match/event in the event preview, or next request in the HAR preview. Shift+F3 moves backward in event and HAR previews; in the plain-text preview it currently still moves forward. Ctrl+Down: next matching file. Ctrl+R: reset. Use the visible buttons if a shortcut is unclear.",
                    "Tab and Shift+Tab move between controls. Space activates focused buttons/checkboxes. Date/time picker fields support Up/Down; Enter applies a picker change and Escape cancels it.",
                    "Native Windows window controls remain available: minimize, maximize/restore, close, Alt+Space for the window menu and Windows snapping."),
                New HelpTopic("Troubleshooting — where did my results go?",
                    "Only one event/request: uncheck first-match mode in Settings → Search, check both record limits, save and rescan. Clear Event tools/HAR tools preview filters. More words highlighted in one event do not mean more events were captured.",
                    "No matches: check the source path, search mode, case sensitivity and search targets. Clear restrictive pre-scan filters, verify UTC dates, and review included extensions/excluded folders. Diagnostics may explain access, archive or body limits.",
                    "More matches expected: a + or partial notice indicates a limit, first-match policy or error. Cancelling retains only work completed so far. Counts can differ because files changed between counting and searching. Increase limits only if you understand the memory/time implications.",
                    "Missing EVTX description: inspect Raw event XML and offline resource guidance. Provider messages may require source-machine resources or exported locale metadata. A missing description is not proof that the event is corrupt.",
                    "HAR body hidden: inspect redaction and body notices. Redaction, disabled Base64 decoding, binary content and size limits can all hide a body. Changes require a new scan.",
                    "Preview unavailable or shortened: check preview size, Diagnostics and WebView2 availability. Do not disable safety limits just to accept an untrusted archive. If reporting a bug, include the app version, relevant settings, expected/actual behavior and a sanitized sample—never upload credentials or private logs.")
            }
            catalog.InsertRange(2, RegexHelpContent.Topics())
            Return catalog
        End Function
    End Class
End Namespace
